// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/casio-sync/ActivityLog.tsx": () => import("../components/mockups/casio-sync/ActivityLog.tsx"),
  "./components/mockups/casio-sync/AuthScreen.tsx": () => import("../components/mockups/casio-sync/AuthScreen.tsx"),
  "./components/mockups/casio-sync/Dashboard.tsx": () => import("../components/mockups/casio-sync/Dashboard.tsx"),
  "./components/mockups/casio-sync/DeviceManager.tsx": () => import("../components/mockups/casio-sync/DeviceManager.tsx")
};
