kind = "mobile"
previewPath = "/"
title = "watch sync pro"
version = "1.0.0"
id = "artifacts/casio-band"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
localPort = 24548
name = "expo"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/casio-band run dev"

[services.env]
PORT = "24548"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/casio-band", "run", "build"]
run = ["pnpm", "--filter", "@workspace/casio-band", "run", "serve"]
